---
title: "Clase 03"
output: html_document
#date: '2022-05-30'
knit: (function(inputFile, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(inputFile,
                    encoding="UTF-8",
                    output_file=file.path(dirname(inputFile), out_dir, 'clase03.html')) })
---

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy('')
```

```
Tibles join, gráficos :
inner_join, left_join, right_join, full_join, semi_join, anti_join
ggplot, geom_point, facet_grid, geom_bar, stat_count, stat_summary
```

Una versión actualizada de este material en : [clase03](https://mar71n.github.io/rconr/clase03.html)

***

```{r, echo=TRUE,  class.source='klippy'}
library(dplyr)
library(readr)
library(ggplot2)
library(sf)
```

***

### Datasets
#### Establecimientos Educativos
```{r, echo=TRUE,  class.source='klippy'}
# https://data.buenosaires.gob.ar/dataset/establecimientos-educativos
# establecimientos <- read_csv("https://cdn.buenosaires.gob.ar/datosabiertos/datasets/ministerio-de-educacion/establecimientos-educativos/establecimientos_educativos_WGS84.csv")
establecimientos <- read_csv("datos/establecimientos_educativos_WGS84.csv")

spec(establecimientos)

head(establecimientos)

names(establecimientos)

names(establecimientos) <- toupper(names(establecimientos))

establecimientos %>% distinct(BARRIO)

c(establecimientos %>% distinct(BARRIO))

n_distinct(establecimientos$BARRIO)
```

```{r, echo=TRUE,  class.source='klippy'}
# poblacion <- read_csv("https://cdn.buenosaires.gob.ar/datosabiertos/datasets/barrios/caba_pob_barrios_2010.csv")
poblacion <- read_csv("datos/caba_pob_barrios_2010.csv")

poblacion %>% count(BARRIO) %>% filter(n != 1)

poblacion %>% distinct(BARRIO)

n_distinct(poblacion$BARRIO)

c(poblacion %>% distinct(BARRIO))

setdiff(establecimientos$BARRIO, poblacion$BARRIO)

setdiff(poblacion$BARRIO, establecimientos$BARRIO)

which(establecimientos[, "BARRIO"] == "MONTSERRAT")
which(poblacion[, "BARRIO"] == "MONSERRAT")

which(establecimientos[, "BARRIO"] == "SAN NIICOLAS")
which(poblacion[, "BARRIO"] == "SAN NICOLAS")

establecimientos[which(establecimientos[, "BARRIO"] == "MONTSERRAT"),"BARRIO"] <- "MONSERRAT"
establecimientos[which(establecimientos[, "BARRIO"] == "SAN NIICOLAS"),"BARRIO"] <- "SAN NICOLAS"

```

***

### Agrupando por barrio, con población
#### *group_by()* , *left_join()*
```{r, echo=TRUE,  class.source='klippy'}
establecimientos %>% group_by(BARRIO) %>% 
  summarise(ESTABLECIMIENTOS = n()) %>% 
  left_join(poblacion) 
```


```{r, echo=TRUE,  class.source='klippy'}
establecimientos %>% group_by(BARRIO) %>% summarise(ESTABLECIMIENTOS = n()) %>%
  left_join(poblacion) 

establecimientos %>% group_by(BARRIO) %>% summarise(ESTABLECIMIENTOS = n()) %>%
  left_join(poblacion) %>%
  mutate(CADA_1000 = (ESTABLECIMIENTOS * 1000) / POBLACION)
```


***
***

#### Un gráfico que ya hicimos, solo cambian los datos
##### Notemos que la sintaxis del gráfico es practicamente idéntica, lo que sí requirió trabajo es armar bien los datos.
```{r, echo=TRUE,  class.source='klippy'}
barrios2 <- st_read("datos/barrios.csv")

barrios3 <- establecimientos %>% group_by(BARRIO) %>% summarise(ESTABLECIMIENTOS = n()) %>%
  left_join(poblacion) %>%
  mutate(CADA_1000 = (ESTABLECIMIENTOS * 1000) / POBLACION)


ggplot(barrios2 %>% left_join(barrios3, by = c("barrio" = "BARRIO") )) + 
  geom_sf(aes(fill=CADA_1000))
```


