---
title: "Clase 01"
output: html_document
#date: '2022-05-30'
knit: (function(inputFile, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(inputFile,
                    encoding="UTF-8",
                    output_file=file.path(dirname(inputFile), out_dir, 'clase01.html')) })
---

```
Instalación, ayuda, búsquedas:
R, CRAN, R-seek, RStudio, install.packages, library
Variables y tipos, importar datos:
vectores, matrices, factores, list, asignación
dataframe, tibles
```


### Instalar:

#### Página principal de R:
[https://www.r-project.org/](https://www.r-project.org/)

Descargas o CRAN lleva a : [https://cran.r-project.org/mirrors.html](https://cran.r-project.org/mirrors.html)

Donde vemos una lista de "mirrors".

De Argentina : El de la [Facultad de Ciencias Astronómicas y Geofísicas - UNLP](https://www.fcaglp.unlp.edu.ar/)

http://mirror.fcaglp.unlp.edu.ar/CRAN/

O uno general https://cloud.r-project.org/ que de alguna manera elije entre los disponibles.

Descargamos el instalador para el SO y arquitectura correspondiente.


### Rtools:
Para algunas instalaciones de paquetes en Windows

para R4.2:
[https://cran.r-project.org/bin/windows/Rtools/rtools42/rtools.html](https://cran.r-project.org/bin/windows/Rtools/rtools42/rtools.html)

para R3.6 o menos:
[https://cran.r-project.org/bin/windows/Rtools/history.html](https://cran.r-project.org/bin/windows/Rtools/history.html)


### Tidyverse:
https://www.tidyverse.org/

### Rstudio - Rmarckdown:
https://rmarkdown.rstudio.com/

### Búsquedas y ayuda:

[https://rseek.org/](https://rseek.org/)

[https://www.rdocumentation.org/](https://www.rdocumentation.org/)

[https://community.rstudio.com/](https://community.rstudio.com/)

[versión en español de Stack Overflow](https://es.stackoverflow.com/)

### Variables y tipos, importar algunos datos:

typeof(1.2)

typeof(1L)

typeof("abc")

typeof(TRUE)

typeof(2+1i)

typeof(sqrt(2))

typeof(sqrt(-1+0i))

typeof(1i * 1i)

Con estos tipos, R es una "calculadora"

precio_anterior = 85.23
precio_actual = 99.0
diferencia = precio_actual - precio_anterior
Que % aumento ? (del precio inicial)
diferencia / precio_anterior * 100
((precio_actual / precio_anterior) - 1) * 100
83.23 * 1.16

aumento <- function(x, y){
  (y - x) / x * 100
}

aumento(precio_anterior, precio_actual)

## Vectores

precios_enero <- c(100, 600, 20000, 45)
precios_marzo <- c(110, 650, 21000, 45)

total_enero <- sum(precios_enero)
total_marzo <- sum(precios_marzo)

aumento(total_enero, total_marzo)

precios_marzo - precios_enero

aumento(precios_enero, precios_marzo)

### Algunos datasets

barrios <- read.csv("https://cdn.buenosaires.gob.ar/datosabiertos/datasets/barrios/barrios.csv")

barrios <- read.csv("barrios.csv")

comunas <- read.csv("https://cdn.buenosaires.gob.ar/datosabiertos/datasets/comunas/comunas.csv")

comunas <- read.csv("comunas.csv")

names(barrios)

str(barrios)

barrios %>% select(!WKT)

barrios %>% select(barrio, comuna)

names(comunas)

str(comunas)

comunas %>% select(COMUNAS, BARRIOS)

readWKT(barrior$WKT[1])
library(ggplot2)
library(sf)
library(dplyr)

barrios2 <- st_read("barrios.csv")
barrios2 <- st_ st_read(barrios)



ggplot(barrios %>% mutate(geometry = WKT)) + 
geom_sf()

