---
title: "Clase 02"
output: html_document
#date: '2022-05-30'
knit: (function(inputFile, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(inputFile,
                    encoding="UTF-8",
                    output_file=file.path(dirname(inputFile), out_dir, 'clase02.html')) })
---

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy('')
```

```
Tibles, filtrar y agrupar:
dplyr, filter, arrange, select, mutate,
summarise, group_by, ungroup,
```

```{r, echo=TRUE,  class.source='klippy'}
library(dplyr)
library(readr)
#install.packages("readr")
library(lubridate)
```

***

### Datase
#### Tomamos de data.buenosaires el registro de vacunaciones:
```{r, echo=TRUE,  class.source='klippy'}
# https://data.buenosaires.gob.ar/dataset/plan-de-vacunacion-covid-19
#vacunas <- read_csv("https://cdn.buenosaires.gob.ar/datosabiertos/datasets/salud/plan-de-vacunacion-covid-19/dataset_total_vacunas.csv")
vacunas <- read_csv("datos/dataset_total_vacunas.csv")
```

#### Una primera mirada, segun lo que esperemos, por lo general alguno de estos:
```{r, echo=TRUE,  class.source='klippy'}
head(vacunas)

summary(vacunas)

str(vacunas)

table(vacunas$GENERO)

table(vacunas$GRUPO_ETARIO)

table(vacunas$VACUNA)
```

***

#### Que pasa con las fechas ?
##### Para esto cargamos la libreria *lubridate*
```{r, echo=TRUE,  class.source='klippy'}
dmy_hms(head(vacunas$FECHA_ADMINISTRACION))

max(dmy_hms(vacunas$FECHA_ADMINISTRACION))
```

***

#### Agregar algun cálculo y seleccionar las columnas de interes
##### mutate() y select()
```{r, echo=TRUE,  class.source='klippy'}
vacunas %>% mutate(total = (DOSIS_1 + DOSIS_2 + DOSIS_3)) %>% select(FECHA_ADMINISTRACION, GENERO, GRUPO_ETARIO, total) %>%
  filter(GENERO == "F")
```

#### Filtrar y ordenar
##### filter() y range()
```{r, echo=TRUE,  class.source='klippy'}
vacunas %>% mutate(total = (DOSIS_1 + DOSIS_2 + DOSIS_3)) %>% select(FECHA_ADMINISTRACION, GENERO, GRUPO_ETARIO, total) %>%
  filter(GRUPO_ETARIO == "51 a 60") %>%
  arrange(desc(total))
```
