---
title: "Gestión de datos en R: herramientas y ejemplos para el trabajo con datos dentro de los equipos de IDECBA"
#author: "mar71n"
#date: "24 de agosto de 2025"
knit: (function(inputFile, encoding) {
  out_dir <- '../docs/apuntes2025';
  rmarkdown::render(inputFile,
                    encoding="UTF-8",
                    output_file=file.path(dirname(inputFile), out_dir, 'apuntes.html')) })
output: html_document
---
## Nivel 1

[Clase 1:]() <!-- // (clase01.html) -->
Introducción al Ecosistema R. 
Instalación de R, RStudio y paquetes (install.packages, library).
Recursos de ayuda (CRAN, R-Seek).
Cómo interpreta R los datos, Estructuras más comunes de nuestros datos. Consumiendo resultados. Creando resultados
Vectores, matrices, listas, factores.
Importación de datos y data frames.
EAH: estructura, cuadros básicos, read_excel

[Clase 2:]() <!-- // (clase02.html) -->
Manipulación de datos con dplyr (filter, select, mutate, group_by).
Gráficos básicos con ggplot2 (geom_bar). aes, stat,  position
EAH: estructura, cuadros básicos, read_excel


[Clase 3:]() <!-- // (clase03.html) -->
Combinar tablas con *_join.
inner_join, left_join, right_join, full_join, semi_join, anti_join 
ggplot, geom_point, facet_grid, geom_bar, stat_count, stat_summary

[Clase 4:]() <!-- // (clase04.html) -->
Manejo de textos (stringr) y fechas (lubridate).
Gráficos para mostrar resultados: coord_flip, geom_smooth


